"""Add newsletter extraction models

Revision ID: 0a3d2a7ef13b
Revises: 
Create Date: 2025-10-15 17:33:02.131099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a3d2a7ef13b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extractions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('days_back', sa.Integer(), nullable=True),
    sa.Column('max_results', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extractions_created_at'), 'extractions', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', 'SUPERADMIN', 'OWNER', name='userrole'), nullable=False),
    sa.Column('tier', sa.Enum('FREE', 'STARTER', 'PRO', 'BUSINESS', 'OWNER', name='usertier'), nullable=False),
    sa.Column('requests_this_month', sa.Integer(), nullable=False),
    sa.Column('requests_reset_at', sa.DateTime(), nullable=True),
    sa.Column('twitter_connected', sa.Boolean(), nullable=False),
    sa.Column('linkedin_connected', sa.Boolean(), nullable=False),
    sa.Column('reddit_connected', sa.Boolean(), nullable=False),
    sa.Column('youtube_connected', sa.Boolean(), nullable=False),
    sa.Column('facebook_connected', sa.Boolean(), nullable=False),
    sa.Column('instagram_connected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('TIKTOK', 'YOUTUBE', 'REDDIT', 'ARTICLE', 'EMAIL', 'BETTING', name='platform'), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('author', sa.String(length=256), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_content_metadata', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'EXTRACTING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=False),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contents_url'), 'contents', ['url'], unique=False)
    op.create_table('email_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extraction_id', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=1024), nullable=False),
    sa.Column('sender', sa.String(length=256), nullable=False),
    sa.Column('date', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_content_extraction_id'), 'email_content', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_email_content_sender'), 'email_content', ['sender'], unique=False)
    op.create_table('newsletters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('digest', sa.Text(), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('source_content_ids', sa.JSON(), nullable=False),
    sa.Column('content_metadata', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracted_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['email_content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_links_content_id'), 'extracted_links', ['content_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_links_content_id'), table_name='extracted_links')
    op.drop_table('extracted_links')
    op.drop_table('newsletters')
    op.drop_index(op.f('ix_email_content_sender'), table_name='email_content')
    op.drop_index(op.f('ix_email_content_extraction_id'), table_name='email_content')
    op.drop_table('email_content')
    op.drop_index(op.f('ix_contents_url'), table_name='contents')
    op.drop_table('contents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_extractions_created_at'), table_name='extractions')
    op.drop_table('extractions')
    # ### end Alembic commands ###
