"""add clerk_user_id to users

Revision ID: 3c6812937dfb
Revises: 1efe193e2389
Create Date: 2025-10-17 19:46:01.137017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c6812937dfb'
down_revision: Union[str, None] = '1efe193e2389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_captures_created_at', table_name='captures')
    op.drop_index('ix_captures_title', table_name='captures')
    op.drop_index('ix_captures_user_id', table_name='captures')
    op.drop_table('captures')
    op.add_column('users', sa.Column('clerk_user_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.drop_column('users', 'clerk_user_id')
    op.create_table('captures',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='captures_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='captures_pkey')
    )
    op.create_index('ix_captures_user_id', 'captures', ['user_id'], unique=False)
    op.create_index('ix_captures_title', 'captures', ['title'], unique=False)
    op.create_index('ix_captures_created_at', 'captures', ['created_at'], unique=False)
    # ### end Alembic commands ###
