"""add user authentication - user_id to extractions and google oauth fields

Revision ID: ac4b2ff42914
Revises: 405f9211eb0a
Create Date: 2025-10-15 19:04:12.584636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac4b2ff42914'
down_revision: Union[str, None] = '405f9211eb0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extractions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_extractions_user_id'), 'extractions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'extractions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('oauth_provider', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('google_email', sa.String(length=320), nullable=True))
    op.add_column('users', sa.Column('google_picture', sa.String(length=512), nullable=True))
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_column('users', 'google_picture')
    op.drop_column('users', 'google_email')
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'oauth_provider')
    op.drop_constraint(None, 'extractions', type_='foreignkey')
    op.drop_index(op.f('ix_extractions_user_id'), table_name='extractions')
    op.drop_column('extractions', 'user_id')
    # ### end Alembic commands ###
